name: Build image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: mabesa/sapphire-dashboard
  
  #AWS_REGION: MY_AWS_REGION                   # set this to your preferred AWS region, e.g. us-west-1
  #ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
  #ECS_SERVICE: MY_ECS_SERVICE                 # set this to your Amazon ECS service name
  #ECS_CLUSTER: MY_ECS_CLUSTER                 # set this to your Amazon ECS cluster name
  #ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  #CONTAINER_NAME: MY_CONTAINER_NAME           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

#permissions:
#  contents: read

jobs:

  dockerize:
    name: Dockerize dashboard and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Rename the image
      - name: Rename the image
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      # Run the dockerization & deployment script
      - name: Build Docker image
        run: |
          docker build --no-cache -t "$IMAGE_NAME:$IMAGE_TAG" .

      # Log in to the Docker registry
      - name: Log in to the Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the image to Dockerhub
      - name: Push the image to Dockerhub
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"
    
