name: Build image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: mabesa/mcass-dashboard

jobs:

  dockerize:
    name: Dockerize dashboard and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Rename the image
      - name: Rename the image
        run: |
          echo "IMAGE_TAG=latest" >> $GITHUB_ENV

      # Run the dockerization & deployment script
      - name: Build Docker image
        run: |
          docker build --no-cache -t "$IMAGE_NAME:$IMAGE_TAG" .

      # Log in to the Docker registry
      - name: Log in to the Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the image to Dockerhub
      - name: Push the image to Dockerhub
        run: |
          docker push "$IMAGE_NAME:$IMAGE_TAG"

